"""
Copyright Matt DeMartino (Stravajiaxen)
Licensed under MIT License -- do whatever you want with this, just don't sue me!

This code attempts to solve
Project Euler (projecteuler.net) Problem #2 Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four
million, find the sum of the even-valued terms.
"""

def main():
    max_num = 4000000
    fibs = [1, 1, 2]
    while(max(fibs) <= max_num):
        fibs.append(sum([fibs[-1], fibs[-2]]))

    tot = 0
    for i in fibs:
        if i % 2 == 0:
            tot += i
    print(tot)

if __name__ == '__main__':
    main()